### ISSUE TITLE
[map-basic] Dynamically refresh vector features

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/elements#16]
We need some way to dynamically update the vector layer features if a property in the app changes - right now the styling gets only applied on map mounted. One option would be to destroy the layer and recreate the layer, but there might be better options - not sure if the functionality from [here](https://github.com/ghettovoice/vuelayers/issues/47#issuecomment-500701752) is already available in the vuelayers version we're using...

**Comment by silvester-pari** [comment]
Here is the location of our current style function, which unfortunately gets only called on mounted and is not yet reactive: https://github.com/EOX-A/elements/blob/main/packages/map-basic/src/VectorStyle.vue

**Comment by lubojr** [comment]
Fixed in https://github.com/EOX-A/elements/commit/748b9fbca2b148caf605eb0c36543b06d85888db - will close when merged to `main`

**Comment by lubojr** [comment]
For dynamtically updating OL style, above fix was done. For dynamically updating Mapbox style, we can not "extend" the mapbox style by highlighting, as the result of OL parsing a mapbox style is a stylefunction, not a style (understandably, as we can set style to depend on vector feature properties). 

So for example for highlighting a workaround as an "option we could investigate in the future" would be to use more raw function stylefunction of ol-mapbox-style https://github.com/openlayers/ol-mapbox-style#stylefunction which accepts already a json with the style, not its url (we could first fetch the style json ourselves, save it to memory and then on-the-fly update the json object (adding/removing parts about different style based on attribute match - aka highlight) and then apply this changed style via stylefunction to already existing vector-tile layer instance.

So far for something as simple as parcel display, we shall be using OL styles definitions.
