### ISSUE TITLE
[map-basic] Mouse zooming does not work properly after migration to vuelayers 0.12.0-rc.21

### ISSUE THREAD

**Issue by lubojr** [EOX-A/elements#32]
With migration to Openlayers 6 + Vuelayers 0.12.x allowing non-integer zoom levels, our zooming stopped working properly (zooming happens in very low increments). I have so far been able to investigate following: Concerned component is https://openlayers.org/en/latest/apidoc/module-ol_interaction_MouseWheelZoom-MouseWheelZoom.html

When passing non-default `useAnchor` parameter as false and constraining zoom levels via `constrainResolution` - either on view or on MouseWheelZoom control (which yield nicer looking and crisp vector tiles anyway), it works fine and is merged now to `main`. The problem is that anchor of zooming is set to center of page, which is a relict of past and does not bring a nice user experience. 

The improvement would be to investigate and solve why the zooming does not work properly without `useAnchor=false`

**Comment by silvester-pari** [comment]
Most likely connected to issue https://github.com/ghettovoice/vuelayers/issues/413.

Reverted the vuelayers package version to `0.12.0-rc.20` for now and removed the MouseWheelZoom hack, let's hope for a fix soon on vuelayers' side :-)
