### ISSUE TITLE
In the latest version cant set projection

### ISSUE THREAD

**Issue by Scartography** [EOX-A/elements#53]
* did the projection for the map config moved?
* in the lower version it was at: https://github.com/EOX-A/elements/blob/%40eox/map-source-select%400.0.6/packages/map-basic/src/MapBasic.vue#L107
* would be nice to have it, assuming that we would like to use smoothing else than mercator

**Comment by silvester-pari** [comment]
From `1.x.x` onwards, the map/view config and layer generation have changed and aren't backwards compatible.

With the new system, you can pass every config prop available in Vuelayers for [vl-map](https://vuelayers.github.io/#/docs/component/map?id=properties) and [vl-view](https://vuelayers.github.io/#/docs/component/view?id=properties) as an object; an example can be found [here](https://eox-a.github.io/elements/examples/map-basic.html#map-with-a-custom-feature).

```
    :mapConfig="{
      'data-projection': 'EPSG:4326', // Projection of input/output plain coordinates in properties, events and etc.
    }"
    :viewConfig="{
      'projection': 'EPSG:3857', //The view internal projection. This is the projection with which OpenLayers component will work.
    }"
```

To see some examples on how to define layers with the new system, check out [this example](https://eox-a.github.io/elements/examples/map-basic.html#simple-layer-selector):
```
      {
        id: 'cloudless',
        title: 'WMTS from Capabilities',
        type: 'tile',
        visible: true,
        source: {
          type: 'wmts-capabilities',
          url: 'https://tiles.maps.eox.at/wmts/1.0.0/WMTSCapabilities.xml',
          layerName: 's2cloudless-2019_3857',
          matrixSet: 'GoogleMapsCompatible',
        },
      },
```

By the way, you can now also use the `sync`modifier to sync back map movements to the corresponding data (worsk with zoom, center and rotation):
```
  <map-basic
    :zoom.sync="zoom"
    :center.sync="center"
    :layers="layers"
    style="height: 100%; width: 100%;"
  />
```
This way, you can e.g. use `center` in a reactive way in the app.

All the other configurations options are available here: https://eox-a.github.io/elements/api/ (WIP).

**Comment by Scartography** [comment]
ah neat, the `custom feature` example was not where I was looking for it :) maybe add it somewhere near the default config example up top? just a suggestion.

Answered, the comment above should close this.
