### ISSUE TITLE
[charts] Tooltip is not at mouse position

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/elements#7]
When hovering over the points of a line chart, the tooltip is sometimes at the center line, sometimes somewhere else - would probably be best to always keep it at mouse position?

**Comment by santilland** [comment]
it should always be at the centerline as we are using the combined tooltip function of chartjs that then shows all datapoints in that "vertical line". I think its kind of cool as it actually changes the content of the tooltip based on what datasets are active or not.
We can change it to the default method where it only shows the value for the point you are hovering,  also fine by me.

**Comment by santilland** [comment]
you can comment out the line:
`mode: 'label',`
then it is solved
